language: python
python:
  - "2.7"
# command to install dependencies
install: 
  - make dependencies
  - pip install coveralls
# install: "pip install -r requirements.txt --use-mirrors"
# command to run tests
script: make test
after_success:
  - coveralls