application: e~hudoraexpress
version: dev
runtime: python27
threadsafe: yes
api_version: 1
default_expiration: "5d"

builtins:
- remote_api: off
- appstats: on
- deferred: on

handlers:
- url: /gaetk_replication/.*
  script: replication.cloudsql.application
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /_ah/login_required
  script: gaetk.login.application

- url: /logout
  script: gaetk.login.application

- url: /gaetk/static
  static_dir: lib/appengine-toolkit/static

- url: /gaetk/.*
  script: .gaetk.defaulthandlers.application

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: .*
  script: main.application
  secure: optional

#error_handlers:
#  - file: templates/error_default.html
#  - error_code: over_quota
#    file: templates/error_over_quota.html
#  - error_code: dos_api_denial
#    file: templates/error_dos_api_denial.html
#  - error_code: timeout
#    file: templates/error_timeout.html

libraries:
- name: jinja2
  version: "2.6"
- name: setuptools
  version: "0.6c11"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?(CHANGES|LICENSE|AUTHORS)
- ^(.*/)?Makefile
- ^(.*/)?requirements\.txt
- ^(.*/)?setup.py
- ^.*/(doc|example|test|bin)s?/.*
- ^(doc|example|test|bin)s?/.*
- ^.+/README.*
- ^(.*/)?lib/.*/(cups-backends|odbc_bridge|softm_express|tests|testsuite)/.*
- ^(.*/)?lib/CentralServices/keys/.*
- ^(.*/)?lib/jinja2/(scripts|custom_fixers_artwork)/.*
- ^(.*/)?lib/google_appengine/.*
- ^(.*/)?lib/gae-sessions/(demo|demo-with-google-logins|docs|tests)/.*
- ^(.*/)?lib/fmtp/printclient/.*
- ^(.*/)?testenv/.*
- ^(.*/)?pythonenv/.*
- ^(.*/)?(CHANGES|LICENSE|AUTHORS)
- transferfromsoftm/.*
